# Generated by Django 3.2.15 on 2022-09-30 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('erollmentno', models.AutoField(primary_key=True, serialize=False)),
                ('Courses', models.CharField(choices=[('bca', 'BCA'), ('bba', 'BBA'), ('bcom', 'BCom')], max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
