# Generated by Django 3.2.15 on 2022-09-30 15:34

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220930_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollmentno',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=11, max_length=11, prefix=''),
        ),
    ]
