# Generated by Django 3.2.15 on 2022-09-30 15:36

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20220930_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='enrollmentno',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=11, max_length=11, prefix='', unique=True),
        ),
    ]
