# Generated by Django 3.2.15 on 2022-10-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20221004_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='isStudent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='isTeacher',
            field=models.BooleanField(default=False),
        ),
    ]
