# Generated by Django 3.2.15 on 2022-10-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
