# Generated by Django 3.2.15 on 2022-10-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
