# Generated by Django 3.2.13 on 2022-10-08 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20221008_1734'),
        ('account', '0012_remove_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentenrolled', to='course.course'),
        ),
    ]
