# Generated by Django 3.2.13 on 2022-10-08 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_student_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Courses',
        ),
    ]
