# Generated by Django 3.2.13 on 2022-10-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Duration', models.IntegerField(default=3)),
                ('Fees', models.CharField(max_length=50)),
            ],
        ),
    ]
