# Generated by Django 3.2.13 on 2022-10-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.IntegerField(default=3, verbose_name='Duration (in Years)'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Fees',
            field=models.CharField(max_length=50, verbose_name='Fees (Per Semister)'),
        ),
    ]
